### ISSUE TITLE
More trajectory info when using hierarchical clustering

### ISSUE THREAD

**Issue by freund17** [ATTPC/ATTPCROOTv2#13]
Currently the trajectories are just a vector of hit-indices.
In the near future this will be replaced by a new class **ATTrajectory**, which will contain the following information:
  - indices of points belonging to that trajectory
  - average curvature
  - start index (index of the point at the very start of the trajectory)
  - end index (because, why not?)
  - length of the trajectory (following the curve; using a
minimum-spanning-tree and shortest path from start to end)
  - centerpoint of the trajectory (average position of all points belonging to that trajectory)
  - main direction (basicly a PCA)

**Comment by Yassid** [comment]
I suggest to modify the existing ATTrack class, for better compatibility with other parts such as the MC fit.
