### ISSUE TITLE
AtTPC20MgDecay clang-tidy output

### ISSUE THREAD

**Issue by anthoak13** [ATTPC/ATTPCROOTv2#146]
AtTPC20MgDecay current outputs ~1000 lines of clang-tidy messages. 

Some of them look like they could be actual bugs, like if statements that always return true such as:
https://github.com/ATTPC/ATTPCROOTv2/blob/b04941773b6a858282650f9f6800f3b703dca6dc/AtGenerators/AtTPC20MgDecay.cxx#L1300
and
https://github.com/ATTPC/ATTPCROOTv2/blob/b04941773b6a858282650f9f6800f3b703dca6dc/AtGenerators/AtTPC20MgDecay.cxx#L1311

**Comment by anthoak13** [comment]
@Ruchi-GADGETII I just got a chance to look through the PR Yassid merged. Are these if statements supposed to be 
```cpp 
if ((0.333 < brp) && (brp <= 1))
```
and
```cpp 
 if (brp == 1)
```

**Comment by Ruchi-GADGETII** [comment]
Hi @anthoak13 , This else if (0.333 < brp <= 1) is supposed to be like this as it is checking the branching ratio in between 0 to 0.333 first and if not then between 0.333 and 1. But the if (brp = 1) (line 1311) should definitely be if (brp == 1). Should I send you the corrected file?

Thanks.

**Comment by anthoak13** [comment]
That double comparison will always return true or false depending on the first comparison only. When it is compiled it will turn into 

`if(.3 < bra <= 1` assuming bra is 0.4 -> `if( true <= 1)`-> if (true).

`if(.3 < bra <= 0.98` assuming bra is 1 -> `if( true <= 0,98)`-> if (false).

Which it sounds like is not the intended behavior

**Comment by anthoak13** [comment]
@Ruchi-GADGETII it might be faster if I make the changes so the class doesn't trigger any of our code linters anymore and then send it to you to check?

**Comment by Ruchi-GADGETII** [comment]
@anthoak13 . Ok then please send me the file and I will compile and check that.
Thanks again!!

**Comment by anthoak13** [comment]
#151 Should fix
