### ISSUE TITLE
S800 behavior breaks visualizer

### ISSUE THREAD

**Issue by anthoak13** [ATTPC/ATTPCROOTv2#179]
https://github.com/ATTPC/ATTPCROOTv2/blob/bc3133ec41747fb30de76957dcec57c61ac93372/AtEventDisplay/AtEventManager.cxx#L436

This function hard codes the branch for AtEvents, and also requires an event to be in the S800 gate by default. That's bad as most data is not S800 and that variable defaults to false it is constantly checking. Old behavior should be the default with an option to turn on gate checking that has to be specified by the user in the macro.

**Comment by anthoak13** [comment]
@Yassid @cnhunt found this bug. It'll make the visualizer basically unusable until fixed. I can fix it this weekend or next week, but I'm traveling for interviews again the rest of the week.

**Comment by Yassid** [comment]
I will disable it until it is fixed. We need the visualizer functional.

**Comment by anthoak13** [comment]
Fixed with introduction of new visualized #181
