### ISSUE TITLE
When I try to install ATTPCROOT, something goes wrong in the last step(make install -j4) and it prompts me that the file fairlogger/Logger.h is not

### ISSUE THREAD

**Issue by JOSHUNA-Z** [ATTPC/ATTPCROOTv2#214]
<img width="627" alt="notfound" src="https://github.com/ATTPC/ATTPCROOTv2/assets/143085225/3a75c879-1f17-42f1-b25b-963786aec8bf">

**Comment by Yassid** [comment]
Could you please provide a little bit more information? This is usually caused by a problem with an environmental variable. Are you pointing to the folder where everything is installed using CMAKE_PREFIX_PATH?

**Comment by Yassid** [comment]
What about FAIRROOTPATH?

By the way, are you FRIB employee?

**Comment by JOSHUNA-Z** [comment]
my FairRoot version is v18.8. ATTPCROOTv2-develop

**Comment by Yassid** [comment]
you also need to export FAIRROOTPATH to point where FairRoot installation is. If you send me an email, I can add you to our Discord group to discuss this.

**Comment by JOSHUNA-Z** [comment]
> you also need to export FAIRROOTPATH to point where FairRoot installation is. If you send me an email, I can add you to our Discord group to discuss this.

It should be this one`export SIMPATH=~/fair_install/FairSoft-nov22/install`

**Comment by Yassid** [comment]
Thats for FairSoft. You also need a variable for FairRoot  (FAIRROOT). It usually points to the folder where FairRoot was installed.

**Comment by JOSHUNA-Z** [comment]
> Thats for FairSoft. You also need a variable for FairRoot (FAIRROOT). It usually points to the folder where FairRoot was installed.

you mean i must add a code` export SIMPATH=~/Fair_install/FairRoot/install'? This is a folder where FairRoot was installed

**Comment by JOSHUNA-Z** [comment]
> Thats for FairSoft. You also need a variable for FairRoot (FAIRROOT). It usually points to the folder where FairRoot was installed.

Thank you so much!

**Comment by JOSHUNA-Z** [comment]
> export FAIRROOTPATH=~/Fair_install/FairRoot/install . That folder has to contain 4 subfolders: bin include lib and something else I dont remember now.

Should I deleted FairRoot and install again?

**Comment by Yassid** [comment]
I think that it will be better if you send me an email showing me how everything is installed. Then I can guide you through the process.

**Comment by Yassid** [comment]
Adding FairLogger::FairLogger into the CMakeList dependencies solved the problem.
