### ISSUE TITLE
Member shadowing

### ISSUE THREAD

**Issue by freund17** [ATTPC/ATTPCROOTv2#6]
In ATHoughSaceLine.cc:
    HistHoughRZ (line 350)
    HoughPar (line 612)
In VMEDecoder.cc:
    CoinReg (line 343)

Is this intended?
If yes, I can fix it to get rid of the warning.

**Comment by Yassid** [comment]
Which are the ones that are actually shadowed? In principle this should work as it is, but feel free to fix the warning.

**Comment by freund17** [comment]
The corresponding member variables (properties of the class) are being shadowed.

**Comment by Yassid** [comment]
Ok, I see it now. Feel free to fix it please.

**Comment by freund17** [comment]
I created a PR: https://github.com/ATTPC/ATTPCROOTv2/pull/9
