### ISSUE TITLE
PCL dependence still causing problems in macos

### ISSUE THREAD

**Issue by hapol** [ATTPC/ATTPCROOTv2#67]
Standard Catalina macos installation with PCL1.8 is not able to compile ATTPCRootv2 with the message
```
[100%] Linking CXX shared library ../lib/libATEventDisplay.dylib
ld: file not found: libpcl_io_ply.1.8.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libATEventDisplay.0.0.0.dylib] Error 1
make[1]: *** [eventdisplayAT/CMakeFiles/ATEventDisplay.dir/all] Error 2
make: *** [all] Error 2
```

despite a
` PCL Support NOT Found: Classes and modules depending on PCL will not be built.
`
message appears when running  cmake

The problem is easily solved in the develop version by removing the CMakeLists.txt line:

`#find_package(PCL 1.8)`

**Comment by anthoak13** [comment]
Cleanup of old issues. PCL removed as dependency
